spring.application.name=auditService

# Cache Configuration
cache.audit.ttl=10
cache.audit.max-size=1000

# Logging Configuration
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{requestId}] %logger - %msg%n
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [reqId=%X{requestId}] [ip=%X{clientIp}] %logger{36} - %msg%n




# Rate Limiting Configuration

# Enable/Disable rate limiting
rate-limit.enabled=true

# Maximum number of requests allowed in one refill period
rate-limit.capacity=10

# Number of tokens added back every refill period
rate-limit.refill-tokens=30

# Refill interval
rate-limit.refill-duration=1m

# Strategy: greedy or interval
rate-limit.refill-strategy=INTERVAL

# HTTP status returned when rate limit exceeded
rate-limit.status-code=429

# Response message
rate-limit.message=Rate limit exceeded. Please try again later.

# How client is identified
# Possible values: IP, API_KEY, USER
rate-limit.client-id-type=IP